version: "3.8"
services:
  client:
    container_name: client
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    depends_on:
      - server
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
