blank_issues_enabled: true
contact_links:
  - name: Discord server
    url: https://discord.gg/A2GdYbwAnw
    about: "Want to be part of this community? Join our Discord server!
      you will get proper help and support in this server."
