name: "📝 Documentation"
description: "Any issue related to documentation report it here!"
title: "docs: <title>"
labels: ["documentation"]
body:
  - type: dropdown
    id: doc_type
    attributes:
      label: Project
      description: In which project should we update or create new documentation?
      options:
        - "Client"
        - "Server"
        - "Core"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description if you want us to update or create new documentation
    validations:
      required: false
  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
