name: "🧪 Tests"
description: "Found a test issue report it here"
title: "test: <title>"
labels: ["tests"]
body:
  - type: dropdown
    id: feat_type
    attributes:
      label: Project
      description: In which project should we write new tests or check on failing tests?
      options:
        - "Client"
        - "Server"
        - "Core"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description if you want us to write new tests or check on failing tests
    validations:
      required: false
  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
